FROM postgres:16

ENV POSTGRES_DB=inventory_manager \
    POSTGRES_USER=postgres \
    POSTGRES_PASSWORD=postgres

# The init script is mounted via docker-compose volume
# COPY db.sql /docker-entrypoint-initdb.d/init.sql

EXPOSE 5432
